apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
  namespace: mediaforge
type: Opaque
stringData:
    host: "http://mediaforge:mediaforge@rabbitmq.mediaforge.svc.cluster.local:15672/"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-rabbitmq-auth
  namespace: mediaforge
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host