apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: mediaforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "15692"
        prometheus.io/path: "/metrics/per-object"
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 15692
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: mediaforge
            - name: RABBITMQ_DEFAULT_PASS
              value: mediaforge
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: mediaforge
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672