apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaledobject
  namespace: mediaforge
spec:
  scaleTargetRef:
    name: worker
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 60
  triggers:
    - type: rabbitmq
      metadata:
        protocol: http
        queueName: jobs.transcode
        mode: QueueLength
        value: "5"
      authenticationRef:
        name: keda-rabbitmq-auth