POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "testsample@example.com",
  "password": "pass"
}


### Login - valid
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Login - wrong password
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "wrongpassword"
}

### Upload a file
POST http://localhost:8080/api/uploads
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyNDNhYWIxMC04ZTAwLTQzZmUtOGU4ZC1hNTVhMGM2MDBiNTciLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc4NjAyNDM4NSwiZXhwIjoxNzg2MDI3OTg1fQ.0YMDOln6GEibZEnCHCNSW_GL2OP7GUorLBTuYZfQyfX2q7L5-y87jfqVgSY0GyPBMSMfmSqfReHHv-6RHkRVRg
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="preview.png
Content-Type: image/png

< C:\Users\Faris\Desktop\FF\Praksa\preview.png
--WebAppBoundary--