POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "testsample@example.com",
  "password": "pass"
}


### Login - valid
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Login - wrong password
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "wrongpassword"
}

### Upload a file
POST http://localhost:8080/api/uploads
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyNDNhYWIxMC04ZTAwLTQzZmUtOGU4ZC1hNTVhMGM2MDBiNTciLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc4NjAyMjExNCwiZXhwIjoxNzg2MDI1NzE0fQ.W-5Q5fcS5gQH47_a9XxvGqDbKmZ_lUVmNkt4Zl6k4T6Zsrnw0vcul5QkFrYCDJr5aMrF3YiHWihutuoUFttqPQ
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="preview.png
Content-Type: image/png

< C:\Users\Faris\Desktop\FF\Praksa\preview.png
--WebAppBoundary--