apiVersion: v1
kind: ConfigMap
metadata:
  name: mediaforge-config
  namespace: mediaforge
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: mediaforge
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: http://minio:9000
  MINIO_PUBLIC_ENDPOINT: http://localhost:9000
  MINIO_BUCKET: mediaforge
  API_PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: mediaforge-secret
  namespace: mediaforge
type: Opaque
stringData:
  DB_USER: mediaforge
  DB_PASSWORD: mediaforge
  RABBITMQ_USER: mediaforge
  RABBITMQ_PASSWORD: mediaforge
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
  JWT_SECRET: d1552be79d689a9a2b61fbc8aa81c95d35e3b73e884677ef12cefaffec3bd181